### ISSUE TITLE
What's wrong with the <style> tag?

### ISSUE THREAD

**Issue by felixakiragreen** [VirtualCSS/planning#8]
I was reading through the React 0.13.2 changelog and I noticed that they added the `scoped` property to the `style` element. Granted that is only supported by Firefox, but why couldn't we do something like this? (Though much more elegant, I just wanted to test my theory..)

``` jsx
render() {
  var random = 'asdfasdf'
  return (
    <div className={random}>
      <style>
        {` .${random} {
            color: white;
            background: red;
          }
        `}
      </style>
      woah...
    </div>
  )
}
```

We can do states, pseudo elements, throw in an auto-prefixer... There must be a catch... what is it?

**Comment by jviereck** [comment]
A few things:
- your solution only works for react. If possible, I hope this project can be used for other projects that are not depending on React as well.
- the `scoped` property is only supported in Firefox as you said - which means a lot of older browsers are not supported
- in your setting, how do you define the styles and pass them to child components?

That said, I like that you raise this issue and it might be worth exploring in the future. However, for the time being, to keep the project simple I believe it is better to define the style definitions external of a <style> tag.

Let me know what you think / if the issue can be closed.

**Comment by totty90** [comment]
You can use [smart-css](https://github.com/hackhat/smart-css) and you get "states, pseudo elements" for free too. Plus works crossbrowser and you have namespaces.

**Comment by jedrichards** [comment]
> in your setting, how do you define the styles and pass them to child components

Isn't this "crossing the boundaries" between components? Strictly speaking shouldn't a component just expose a props-based API for adjusting its layout (like SUITCSS modifiers) rather than allow arbitrary styles to be passed down into it? Or am I misunderstanding?
